add linkerd example with header based routing
argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi pull request #91
Opened 2024-11-11 13:42 UTC by AlonGluz

2024-11-14 12:03 UTC, AlonGluz commented
@kostis-codefresh Anything wrong with this PR?

2024-11-14 12:56 UTC, kostis-codefresh commented on examples/linkerd-header-based/README.md
> +## Step 10 - Patch the rollout to see the canary deployment
This is great. But in this example we also want to test header based routing specifically. How do we know that it works?

Can we add 2 examples of "curl" commands here, one with the header and one without the header to see what happens?

2024-11-14 12:57 UTC, kostis-codefresh requested changes
I think we need some extra instructions in the README specifically for header based routing.

2024-12-08 16:25 UTC, AlonGluz commented
@kostis-codefresh sure, I'll take care of it 👍🏻

2024-12-13 13:10 UTC, AlonGluz commented
@kostis-codefresh I've applied the PR comments and tested it with L5d version 2.14.10, LMK if there are any other blockers

2024-12-13 13:37 UTC, merged